config/routes.rb
Rails.application.routes.draw do
  resources :popcorns

end

app/models/popcorn.rb
class Popcorn < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/popcorns_controller.rb
class PopcornsController < ApplicationController
  before_action :set_popcorn, only: [:show, :edit, :update, :destroy]

  # GET /popcorns
  # GET /popcorns.json
  def index
    @popcorns = Popcorn.all
  end

  # GET /popcorns/1
  # GET /popcorns/1.json
  def show
  end

  # GET /popcorns/new
  def new
    @popcorn = Popcorn.new
  end

  # GET /popcorns/1/edit
  def edit
  end

  # POST /popcorns
  # POST /popcorns.json
  def create
    @popcorn = Popcorn.new(popcorn_params)

    respond_to do |format|
      if @popcorn.save
        format.html { redirect_to @popcorn, notice: 'Popcorn was successfully created.' }
        format.json { render :show, status: :created, location: @popcorn }
      else
        format.html { render :new }
        format.json { render json: @popcorn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /popcorns/1
  # PATCH/PUT /popcorns/1.json
  def update
    respond_to do |format|
      if @popcorn.update(popcorn_params)
        format.html { redirect_to @popcorn, notice: 'Popcorn was successfully updated.' }
        format.json { render :show, status: :ok, location: @popcorn }
      else
        format.html { render :edit }
        format.json { render json: @popcorn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /popcorns/1
  # DELETE /popcorns/1.json
  def destroy
    @popcorn.destroy
    respond_to do |format|
      format.html { redirect_to popcorns_url, notice: 'Popcorn was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_popcorn
      @popcorn = Popcorn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def popcorn_params
      params.require(:popcorn).permit(:flavor, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/popcorns_helper.rb
module PopcornsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>小粋</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">小粋</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/popcorns">ポップコーン一覧</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    Rails Girls 2015
  </div>
</footer>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>

</body>
</html>

app/views/popcorns/_form.html.erb
<%= form_for(@popcorn) do |f| %>
  <% if @popcorn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@popcorn.errors.count, "error") %> prohibited this popcorn from being saved:</h2>

      <ul>
      <% @popcorn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flavor %><br>
    <%= f.text_field :flavor %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/popcorns/edit.html.erb
<h1>Editing popcorn</h1>

<%= render 'form' %>

<%= link_to 'Show', @popcorn %> |
<%= link_to 'Back', popcorns_path %>

app/views/popcorns/index.html.erb
<h1>Listing popcorns</h1>

<table>
  <thead>
    <tr>
      <th>Flavor</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @popcorns.each do |popcorn| %>
      <tr>
        <td><%= image_tag(popcorn.picture_url, width: 20) if popcorn.picture.present? %></td>
        <td><%= popcorn.flavor %></td>
        <td><%= popcorn.description %></td>
        <td><%= link_to 'Show', popcorn %></td>
        <td><%= link_to 'Edit', edit_popcorn_path(popcorn) %></td>
        <td><%= link_to 'Destroy', popcorn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Popcorn', new_popcorn_path %>

app/views/popcorns/new.html.erb
<h1>New popcorn</h1>

<%= render 'form' %>

<%= link_to 'Back', popcorns_path %>

app/views/popcorns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flavor:</strong>
  <%= @popcorn.flavor %>
</p>

<p>
  <strong>Description:</strong>
  <%= @popcorn.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@popcorn.picture_url, width: 300) if @popcorn.picture.present? %>
</p>

<%= link_to 'Edit', edit_popcorn_path(@popcorn) %> |
<%= link_to 'Back', popcorns_path %>